### ISSUE TITLE
Is it possible to make this work with Switch?

### ISSUE THREAD

**Issue by pooppooppoopoop** [Pentalex/COTL-SaveDecryptor#1]
[qwerty.zip](https://github.com/Pentalex/COTL-SaveDecryptor/files/9333681/qwerty.zip)

Wondering if it's possible to make this work with Switch saves. I already attempted to turn the save into a JSON file and then convert it but that did nothing. The file itself is just a simple text document that looks similar to PC saves so I was wondering if it was possible somehow, thanks! Uploading my Switch save too if you want to look at it.

**Comment by pentalex** [comment]
Looks like it uses a different method for encryption, then. Usually encrypted save files all start with the letter "E" as the first bit but here I don't see that.
I'm still relatively new to reverse engineering (this was my first succesful try at reverse engineering a games code)
I have no idea if the tools I'm familiar with using would work on Unity games exported to Nintendo Switch.
If anyone else has any insight on this, feel free to comment on this and I'll take a look but it's a little out of my area for now. Sorry!

**Comment by pooppooppoopoop** [comment]
Thanks for the quick answer, btw some people were talking to you on GBAtemp too with other questions!

**Comment by okok7711** [comment]
Switch Saves are just gzipped json files with a 0x5a 0x42 prefix if anyone is still wondering
