### ISSUE TITLE
Large Save File Issues

### ISSUE THREAD

**Issue by JimJamTTM** [Pentalex/COTL-SaveDecryptor#3]
When inputting my save file, I get an error, "Out of Memory." I have tried multiple browsers, Firefox, Chrome, Vivaldi, and Edge, all with the same result.

My save file is quite large, at 871,959 lines and 106MB in size.

I believe this to be a browser limitation.

If I am correct, is there the possibility of a stand-alone application that can be run locally?

**Comment by fennectech** [comment]
hmmm  thats tricky   this is an HTML thing  you might be able to get arround it by compiling it into an electron app
but idk

**Comment by pentalex** [comment]
I can take a look at making it into a Python console app, it would probably work then. 
The algorithm to decode is pretty simple.

**Comment by fennectech** [comment]
Any chance of getting support for decrypting the switch saves?
  I uploaded some here anyone with a modded console can use your tool if it supported switch

**Comment by pentalex** [comment]
> Any chance of getting support for decrypting the switch saves? I uploaded some here anyone with a modded console can use your tool if it supported switch

If you're gonna recommend another suggestion, please post it in a seperate issue. Besides, I have already answered this question in a seperate issue. No, I won't be supporting switch saves as they encrypt those saves differently and I have little experience with reverse engineering Switch based unity games.

**Comment by pentalex** [comment]
To answer the original question in this thread, try using this program for larger save files:
https://github.com/Moonkis/CoTLMindReader
