### ISSUE TITLE
Implement encryptor

### ISSUE THREAD

**Issue by EgorZotov** [Pentalex/COTL-SaveDecryptor#4]
Hey man! Thanks for this tool it is really cool to check save states. But the question is: how to put them back in game? Should i encrypt them back or i can put them decrypted in saves directory?

**Comment by pentalex** [comment]
The decrypted files can be succesfully read by the PC Version of Cult of the Lamb, so you do not need to reencrypt them.

**Comment by EgorZotov** [comment]
> The decrypted files can be succesfully read by the PC Version of Cult of the Lamb, so you do not need to reencrypt them.

You are mad lad. I faced softlock with always low illness meter. Through analysing save file i found that invisible corpses stacked up in my hub. Thanks mate, now it is fixed and I can finish the game! (all cultists died from illness but i can always get a new ones  😈)
